apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: {{ .Values.nexus.image }}
          ports:
            - containerPort: 8081
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: nexus-data
              mountPath: "/mnt/data/nexus"
          securityContext:
            allowPrivilegeEscalation: false

      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
