apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      initContainers:
        - name: init-nexus-permissions
          image: busybox
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "Setting permissions for /nexus-data"
              chown -R 1000:1000 /nexus-data || echo "chown failed"
              chmod -R 755 /nexus-data || echo "chmod failed"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          securityContext:
            runAsUser: 0  # root needed for chown
      containers:
        - name: nexus
          image: sonatype/nexus3:3.71.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: nexus-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nexus-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexus-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          livenessProbe:
            httpGet:
              path: /service/metrics
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /service/metrics
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
