apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus            # Avoid default namespace
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.71.0   # Use a fixed version tag
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: nexus-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nexus-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexus-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: nexus-data
              mountPath: "/mnt/data/nexus"
          readinessProbe:
            httpGet:
              path: /service/metrics
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
