apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: nexus
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: init-permissions
          image: busybox
          command:
            - sh
            - -c
          args:
            - |
              echo "Fixing permissions for PostgreSQL volume"
              chown -R 999:999 /var/lib/postgresql/data || echo "chown failed"
              chmod 700 /var/lib/postgresql/data || echo "chmod failed"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 0  # root is required to change ownership
      containers:
        - name: postgresql
          image: postgres:13
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "nexusdb"
            - name: POSTGRES_USER
              value: "nexus"
            - name: POSTGRES_PASSWORD
              value: "nexuspassword"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
