apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 200
      initContainers:
        - name: init-nexus-permissions
          image: busybox
          command:
            - sh
            - -c
          args:
            - |
              echo "Setting correct permissions for Nexus"
              chown -R 200:200 /nexus-data || echo "chown failed"
              chmod -R 755 /nexus-data || echo "chmod failed"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          securityContext:
            runAsUser: 0  # root needed to change ownership
      containers:
        - name: nexus
          image: sonatype/nexus3:3.71.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          livenessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          securityContext:
            runAsUser: 200
            runAsGroup: 200
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
