apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: nexus  # Use custom namespace
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:  # Pod-level security context
        runAsNonRoot: true
        fsGroup: 1000
      automountServiceAccountToken: false  # Disable service account token mount
      containers:
        - name: postgresql
          image: postgres:13  # Fixed version
