apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: nexus  # Use custom namespace
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      automountServiceAccountToken: false
      initContainers:
        - name: init-permissions
          image: busybox
          command:
            - sh
            - -c
          args:
            - |
              echo "Fixing permissions for PostgreSQL"
              chown -R 1000:1000 /mnt/data/postgresql || echo "chown failed"
              chmod 700 /mnt/data/postgresql || echo "chmod failed"
          volumeMounts:
            - name: postgresql-data
              mountPath: /mnt/data/postgresql
          securityContext:
            runAsUser: 0  # Root required for chown
      containers:
        - name: postgresql
          image: postgres:13
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "nexusdb"
            - name: POSTGRES_USER
              value: "nexus"
            - name: POSTGRES_PASSWORD
              value: "nexuspassword"
          volumeMounts:
            - name: postgresql-data
              mountPath: "/var/lib/postgresql/data"
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
