apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: nexus
  labels:
    app: nexus
stringData:
  POSTGRES_USER: "nexus"
  POSTGRES_PASSWORD: "nexuspassword"
  POSTGRES_DB: "nexusdb"
