apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus  # Specify the namespace here
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb  # Set NLB as the load balancer type
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
